version: "2.3"

services:
  web:
    build:
      context: .
      dockerfile: Prod.Dockerfile
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    restart: unless-stopped
    mem_limit: 3.1g
    mem_reservation: 2.4g
    cpus: 1.25
  proxy:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
        - web
    ports:
        - "80:80"
    restart: always
