import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  // Truncate all existing tables
  await knex.raw('TRUNCATE TABLE athletes CASCADE');
  await knex.raw('TRUNCATE TABLE businesses CASCADE');

  await knex("athletes").insert([
    {
      id: 0,
      first_name: "Hunter",
      last_name: "Solano",
      school: "",
      email: "hunter.solano@yahoo.com",
      password: "",
      phone: "(254) 300-1903",
      location: knex.raw("POINT (-97.21734999999995, 31.391550000000052)"),
      address: "",
      city: "Lorena",
      state: "TX",
      zip: "",
      image_url: "",
    },
    {
      id: 1,
      first_name: "Mariah",
      last_name: "Solano",
      school: "",
      email: "mariah.andreana@yahoo.com",
      password: "",
      phone: "(254) 424-5859",
      location: knex.raw("POINT (-98.49460999999997, 29.42458000000005)"),
      address: "",
      city: "San Antonio",
      state: "TX",
      zip: "",
      image_url: "",
    },
    {
      id: 2,
      first_name: "Tyon",
      last_name: "Davis",
      school: "",
      email: "tyondavis99@gmail.com",
      password: "",
      phone: "(405) 833-1293",
      location: knex.raw("POINT (-97.52106999999995, 35.472030000000075)"),
      address: "",
      city: "Oklahoma City",
      state: "OK",
      zip: "",
      image_url: "",
    },
    {
      id: 3,
      first_name: "Luke",
      last_name: "Jeffus",
      school: "University of Tulsa",
      email: "lej6683@utulsa.edu",
      password: "",
      phone: "(918) 845-0226",
      location: knex.raw("POINT (-96.10842999999994, 36.13966000000005)"),
      address: "",
      city: "Sand Springs",
      state: "OK",
      zip: "",
      image_url: "",
    },
    {
      id: 4,
      first_name: "Sean",
      last_name: "Korsmo",
      school: "",
      email: "skorsmo18@gmail.com",
      password: "",
      phone: "(701) 202-1926",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 5,
      first_name: "Everitt",
      last_name: "Rogers",
      school: "University of Tulsa",
      email: "footballeveritt@gmail.com",
      password: "",
      phone: "(254) 289-1610",
      location: knex.raw("POINT (-95.99351999999999, 36.15011000000004)"),
      address: "",
      city: "Tulsa",
      state: "OK",
      zip: "",
      image_url: "",
    },
    {
      id: 6,
      first_name: "Julia",
      last_name: "Richard",
      school: "",
      email: "julia.b.richard7@gmail.com",
      password: "",
      phone: "(405) 535-5032",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 7,
      first_name: "Jayda",
      last_name: "Gibson",
      school: "University of Tulsa",
      email: "jaydagibson02@gmail.com",
      password: "",
      phone: "(817) 880-9568",
      location: knex.raw("POINT (-95.9445679820816, 36.152037003148365)"),
      address: "800 S Tucker Dr",
      city: "Tulsa",
      state: "OK",
      zip: "74104",
      image_url: "",
    },
    {
      id: 8,
      first_name: "Keagan",
      last_name: "Perez",
      school: "",
      email: "kjperez22@gmail.com",
      password: "",
      phone: "(407) 274-7424",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 9,
      first_name: "Evan",
      last_name: "Sanni-Thomas",
      school: "",
      email: "east7203@gmail.com",
      password: "",
      phone: "(832) 482-5449",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 10,
      first_name: "Jon-Michael",
      last_name: "Terry",
      school: "",
      email: "jonterry8221@gmail.com",
      password: "",
      phone: "(918) 850-1067",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 11,
      first_name: "Canon",
      last_name: "Peters",
      school: "",
      email: "canonp4@gmail.com",
      password: "",
      phone: "(214) 493-5317",
      location: knex.raw("POINT (-95.99351999999999, 36.15011000000004)"),
      address: "",
      city: "Tulsa",
      state: "OK",
      zip: "",
      image_url: "",
    },
    {
      id: 12,
      first_name: "Bedirhan",
      last_name: "Celayir",
      school: "",
      email: "",
      password: "",
      phone: "",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 13,
      first_name: "Jonah",
      last_name: "Anderson",
      school: "",
      email: "jonahando@gmail.com",
      password: "",
      phone: "(208) 661-4131",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 14,
      first_name: "UTD",
      last_name: "CS - Athlete",
      school: "",
      email: "hunter@rattled.co",
      password: "",
      phone: "",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
  ]);
  await knex("businesses").insert([
    {
      id: 0,
      business_name: "Waco Drip",
      first_name: "Hunter",
      last_name: "Solano",
      email: "info@wacodrip.com",
      password: "",
      phone: "(254) 300-1903",
      location: knex.raw("POINT (-97.22763803658431, 31.458891020835793)"),
      address: "2901 Keathley Dr",
      city: "Lorena",
      state: "TX",
      zip: "76655",
      image_url: "",
    },
    {
      id: 1,
      business_name: "Inheritance Juicery",
      first_name: "",
      last_name: "",
      email: "",
      password: "",
      phone: "",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 2,
      business_name: "UTD CS",
      first_name: "UTD",
      last_name: "CS - Business",
      email: "hello@huntersolano.com",
      password: "",
      phone: "",
      location: null,
      address: "",
      city: "",
      state: "",
      zip: "",
      image_url: "",
    },
    {
      id: 3,
      business_name: "Soul Training",
      first_name: "Fred",
      last_name: "Solis",
      email: "drew.solano@gmail.com",
      password: "",
      phone: "(254) 742-8522",
      location: knex.raw("POINT (-97.74352999999996, 31.434900000000027)"),
      address: "123 Cherry St",
      city: "Gatesville",
      state: "TX",
      zip: "76655",
      image_url: "",
    },
  ]);
}
