{
 "title": "AR_Metrics",
 "description": "This dashboard has key metrics related to Business ,Athlete and Campaigns.",
 "time": { "from": "2021-04-04T05:00:00.000Z", "to": "2024-04-05T04:59:59.000Z" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Total Atheletes",
   "type": "gauge",
   "description": "Total Athlete Signed",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Count\" FROM athletes LIMIT 50 "
    }
   ]
  },
  {
   "title": "Business Deals",
   "type": "gauge",
   "description": "Count of Business deals in inception",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Count\" FROM businesses LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Campaign",
   "type": "gauge",
   "description": "Total Campaigns",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) + 10 from campaigns "
    }
   ]
  }
 ]
}